src/Entity/Products.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Products
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Destination = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(length: 255)]
    private ?string $illustration = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDestination(): ?string
    {
        return $this->Destination;
    }

    public function setDestination(string $Destination): self
    {
        $this->Destination = $Destination;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getIllustration(): ?string
    {
        return $this->illustration;
    }

    public function setIllustration(string $illustration): self
    {
        $this->illustration = $illustration;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }
    public function setTitle(string $title): self
    {
        $this->title = $title;
        return $this;
    }


    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCategory(): ?category
    {
        return $this->category;
    }

    public function setCategory(?category $category): self
    {
        $this->category = $category;

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;


use App\Classe\Cart;
use App\Entity\Product;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

class CartController extends AbstractController
{
    private $entityManager;
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

//    *************************************************  PANIER  *******************************************************
    #[Route('/panier', name: 'app_cart')]
    public function index(Cart $cart): Response
    {
        return $this->render('cart/index.html.twig', [
                'cart' => $cart->getFull()

        ]);
    }

//    ************************************************ ADD CART ********************************************************

    #[Route("/cart/add/{id<\d+>}", name: "add_cart")]
    //passer $id dans la function add => paramètre de ma route 'cart/add{$id}' afin de pouvoir l'exploiter
    public function add(Cart $cart,int $id): Response
    {
        //faire un cart add et donner l'id du panier et pour cela créer une function add dans la classe cart
        $cart->add($id);
//        return $this->render('cart/index.html.twig');
        return $this->redirectToRoute('app_cart');
    }

// **************************************************  REMOVE  *********************************************************

    #[Route('/cart/remove', name: 'remove_cart')]
        public function remove(Cart $cart): Response
    {
        $cart->remove();

        return $this->redirectToRoute('app_products');
    }

//**************************************************  DELETE  **********************************************************

    #[Route('/cart/delete/{id}', name: 'delete_cart')]
    public function delete(Cart $cart, int $id): Response
    {
        $cart->delete($id);

        return $this->redirectToRoute('app_cart');
    }

//*************************************************  DECREASE  *********************************************************

    #[Route('/cart/decrease/{id}', name: 'decrease_cart')]
    public function decrease(Cart $cart, int $id): Response
    {
        $cart->decrease($id);

        return $this->redirectToRoute('app_cart');
    }

}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon Panier{% endblock %}

{% block body %}

        <div class="table px-5">
            <div class="titleCart">
                <h1>Mon panier</h1>

                Retrouver l'ensemble des produits que vous avez ajouté à votre panier.
                <hr>
    {% if cart|length > 0 %}
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">illustration</th>
                        <th scope="col">Départ</th>
                        <th scope="col">Destination</th>
                        <th class="text-center" scope="col">Nombre de personne(s)</th>
                        <th scope="col">Prix</th>
                        <th scope="col">Total</th>

                    </tr>
                    </thead>
                    <tbody>
                    {% set total = null %}
                    {% for product in cart %}
                    <tr>
                        <th>
                            <a title="Revenir sur la page des destinations" href="{{ path('app_products') }}"><img src="../uploads/{{ product.product.illustration }}" alt="{{ product.product.destination }}" height="50px"></a>

                        </th>
                        <td>{{ product.product.depart }}</td>
                        <td>{{ product.product.destination }}</td>

                        <td class="modif text-center">

                            <a title="Supprimer une personne" href="{{ path('decrease_cart', {'id' : product.product.id} ) }}">
                                <img src="{{ asset('build/images/Icon/moins.png') }}" width="20px" alt="Supprimer une quantité">
                            </a>
                               {{ product.quantity }}
                            <a title="Ajouter une personne" href="{{ path('add_cart', {'id' : product.product.id}) }}">
                                <img src="{{ asset('build/images/Icon/plus.png') }}" width="20px" alt="Rajouter une quantité">
                            </a>
                        </td>
                        <td>{{ (product.product.price /100)|number_format(2, ',', '') }} €</td>
                        <td>{{ ((product.product.price * product.quantity) /100)|number_format(2, ',', '') }} €</td>
                        <td class="delete" width="5%">
                            <a href="{{ path('delete_cart', {'id' : product.product.id}) }}">
                                <img src="{{ asset('build/images/Icon/delete.png') }}" width="20px" alt="Supprimer mon produit">
                            </a>

                        </td>
                    </tr>

                        {% set total = total + (product.product.price * product.quantity) %}
                    {% endfor %}

                    </tbody>
                </table>
                <div class="total text-end">
            {#      <b>Nombre de produit :</b> {{ cart|length }}<br/>#}
                    <b>Total de mon panier :</b>   {{ (total /100)|number_format(2, ',', '') }} €

                    <div class="bouton mt-5">
                        <a href="{{ path('app_account_address_add') }}" class="btn btn-success btn-block">Valider mon panier</a>
                    </div>
                </div>

            </div>
        </div>
    {% else %}

        <div class="message">
            <p><b>Votre panier est vide.  <a href="{{ path('app_products') }}">choisir une autre destination ?</a></b></p>
        </div>


    {% endif %}

{% endblock %}