src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Boolean;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]


class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(type: 'boolean')]
    private bool $isVerified = false;

    #[ORM\Column(length: 255)]
    private ?string $Lastname = null;

    #[ORM\Column(length: 255)]
    private ?string $Firstname = null;

    #[ORM\Column(length: 20)]
    private ?string $Telephone = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Address::class)]
    private Collection $addresses;

    public function __construct()
    {
        $this->addresses = new ArrayCollection();
    }

//    #[ORM\OneToOne(mappedBy: 'user', cascade: ['persist', 'remove'])]
//    private ?Cart $cart = null;

//    #[ORM\Column]
//    private ?bool $IsVerified = null;
//    private $Is_Verified;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }


    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->Lastname;
    }

    public function setLastname(string $Lastname): self
    {
        $this->Lastname = $Lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->Firstname;
    }

    public function setFirstname(string $Firstname): self
    {
        $this->Firstname = $Firstname;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->Telephone;
    }

    public function setTelephone(string $Telephone): self
    {
        $this->Telephone = $Telephone;

        return $this;
    }

    /**
     * @return Collection<int, Address>
     */
    public function getAddresses(): Collection
    {
        return $this->addresses;
    }

    public function addAddress(Address $address): self
    {
        if (!$this->addresses->contains($address)) {
            $this->addresses->add($address);
            $address->setUser($this);
        }

        return $this;
    }

    public function removeAddress(Address $address): self
    {
        if ($this->addresses->removeElement($address)) {
            // set the owning side to null (unless already changed)
            if ($address->getUser() === $this) {
                $address->setUser(null);
            }
        }

        return $this;
    }

    public function setCart(\App\Classe\Cart $cart)
    {
    }
}

src/Controller/AccountAddressController.php
<?php

namespace App\Controller;

use App\Entity\Address;
use App\Form\AddressType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AccountAddressController extends AbstractController
{
    private $entityManager;
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    #[Route('/compte/adresses', name: 'app_account_address')]
    public function index(): Response
    {

        return $this->render('account_address/index.html.twig');
    }

//******************************************  ADD ADDRESSES  ***********************************************************

    #[Route('/compte/ajouter-une-adresse', name: 'app_account_address_add')]
    public function add(Request $request): Response
    {
        $address = new Address();
        $form = $this->createForm(AddressType::class, $address);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $address->setUser($this->getUser());
            $this->entityManager->persist($address);
            $this->entityManager->flush();
            return $this->redirectToRoute('app_account_address');
        }
//            dd($address);
        return $this->render('account_address/address_form.html.twig', [
            'form' => $form->createView()
        ]);
    }

//******************************************  modifier adresse  ********************************************************
    #[Route('/compte/modifier-une-adresse/{id}', name: 'app_account_address_edit')]
    public function edit(Request $request, $id): Response
    {
        $address = $this->entityManager->getRepository(Address::class)->findOneById($id);

        if (!$address || $address->getUser() != $this->getUser()) {
            return $this->redirectToRoute('app_account_address');
        }

        $form = $this->createForm(AddressType::class, $address);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->flush();
            return $this->redirectToRoute('app_account_address');
        }
//            dd($address);
        return $this->render('account_address/address_form.html.twig', [
            'form' => $form->createView()
        ]);
    }

//***********************************************  Supprier adresse  ***************************************************
    #[Route('/compte/supprimer-une-adresse/{id}', name: 'app_account_address_delete')]
    public function delete($id): Response
    {
        $address = $this->entityManager->getRepository(Address::class)->findOneById($id);

//        si l'adresse existe et que l'utilisateur concerné sinon je ne pourrais pas supprimer l'adresse
        if ($address && $address->getUser() == $this->getUser()) {
//            passer l'adresse à supprimer avec remove
            $this->entityManager->remove($address);
//            je valide
            $this->entityManager->flush();
        }
//        rediriger vers app account address soit la page en cours
        return $this->redirectToRoute('app_account_address');
    }


}

templates/account_address/address_form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une adresse{% endblock %}

{% block body %}


    <section id="road">
        <div class="addresses">
            <div class="container">
                <h1>Gérer mes adresses</h1>
                <p>
                    <a href="{{ path('app_account_address') }}">Retour</a>
                </p>
                <hr>

                {{ form_start(form) }}
                    <div class="row">
                        <div class="col-6">{{ form_row(form.name) }}</div>
{#                        <div class="col-md-6">{{ form_row(form.company) }}</div>#}
                        <div class="col-md-6">{{ form_row(form.lastname) }}</div>
                        <div class="col-md-6">{{ form_row(form.firstname) }}</div>
                        <div class="col-md-6">{{ form_row(form.phone) }}</div>
                        <div class="col-md-6">{{ form_row(form.address) }}</div>
                        <div class="col-md-6">{{ form_row(form.postal) }}</div>
                        <div class="col-md-6">{{ form_row(form.city) }}</div>

                        <div class="col-md-6">{{ form_row(form.country) }}</div>
                    </div>
                {{ form_end(form) }}

            </div>
        </div>
    </section>




{% endblock %}

templates/account_address/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes adresses{% endblock %}

{% block body %}


    <section id="road">
        <div class="adresses">
            <div class="container">
                <a href="{{ path('app_account_address_add') }}" class="btn btn-info float-end">Ajouter une adresse</a>
                <h1>Mes adresses</h1>
                <a href="{{ path('app_account') }}">Retour</a>
                <a href="{{ path('app_account_address_add') }}" class="btn btn-info float-end">Paiements</a>

                <hr>
                {% if app.user.addresses|length == 0 %}
                    <p class="text-center">
                        Vous n'avez pas encore ajouté d'adresse dans votre compte client. Pour ajouter une, veuillez
                        <a href="">cliquer ici</a>
                    </p>
                {% else %}
                    <div class="row">
                        {% for address in app.user.addresses %}
                            <div class="col-md-4">
                                <div class="card" style="width: 18rem;">
                                    <div class="card-body">
                                        <h5 class="card-title">{{ address.lastname }}</h5>
                                        <p class="card-text">
                                            {{ address.address }},<br/>
                                            {{ address.postal }} - {{ address.city }} - {{ address.country }}
                                        </p>
                                        <a href="{{ path('app_account_address_edit', {'id' : address.id}) }}">Modifier</a> | <a href="{{ path('app_account_address_delete', { 'id' : address.id }) }}">Supprimer</a>
                                    </div>
                                </div>
                            </div>

                        {% endfor %}
                    </div>

                {% endif %}

            </div>
        </div>
    </section>




{% endblock %}